---
name: Test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Clear Go cache (macOS fix)
      run: go clean -cache
    - name: Test
      run: go test -a -count=1 -v ./...
